site_name: Voice Enabled Chatbot using Node-RED
theme:
    name: readthedocs
nav:
    # - Home: 'index.md'
    - 'Step 1: Create ChatBot using Watson Assistant': './Solution-Starter-Kit-Communication-2020/assistant/README.md'
    - 'Step 2: Adding Webhooks to Watson Assistant using IBM Functions' : 'Solution-Starter-Kit-Communication-2020/webhook/README.md'
    - 'Step 3: Create Voice Enabled ChatBot using Node-RED': 'Solution-Starter-Kit-Communication-2020/node-red/README.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
